name: Build Sphinx Docs
on:
  push:
    branches:
      - master
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install doc deps
        run: |
          python -m pip install --upgrade pip
          pip install sphinx furo sphinx-rtd-theme myst-parser sphinx-autoapi sphinx-argparse

      - name: Clean build dir
        run: rm -rf docs/_build

      - name: Build HTML (full rebuild)
        run: sphinx-build -b html -a -E docs docs/_build/html

      - name: Build HTML
        run: |
          sphinx-build -b html -v docs docs/_build/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: docs/_build/html
          github_token: ${{ secrets.GITHUB_TOKEN }}